var lp = {
  titleHead: "Green Earth Naturals Energy Enzymes",
  titleBody: "Green Earth Naturals",
  titleBody2: "Energy Enzymes",
  productLink: "http://www.genaturals.com/NEW-Energy-Enzymes-With-Veggie-Caps.html",
  category: "Supplements",
  zoom1: "https://fs.siteor.com/wellness/files/healthHighwayNewLP/zoom1.jpg?1520432823",
  zoom2: "https://fs.siteor.com/wellness/files/healthHighwayNewLP/zoom2.jpg?1520432823",
  zoom3: "https://fs.siteor.com/wellness/files/healthHighwayNewLP/zoom3.jpg?1520432822",
  zoom4: "https://fs.siteor.com/wellness/files/healthHighwayNewLP/zoom4.jpg?1520432824",
  description: "If you feel tired and bloated after meals ... here is the perfect pair of supplements to help bring your digestive system back up to speed. Energy Enzymes help break down food after you’ve eaten, whilst Energy Probiotic Defense help restore the good bacteria to your intestines. Together they’re a welcome boost for many a digestive system.",
  optional-slogan: "FREE Energy Probiotic Defense",
  msrpPrice: "$84.90",
  yourPrice: "$44.95",
  save: "47%",
  buttonSrc: "https://fs.siteor.com/wellness/files/amafruitsNewLP/buynowbutton.jpg?1520435087",
  useCode: "XXXX",
  additionalInfos: [
    {"additional-info": "Helps reduce bloatedness and tiredness after meals - thus increasing energy levels"},
    {"additional-info": "Enables your body to absorb the maximum nutrition from your food - giving you the best from what you eat"},
    {"additional-info": "Helps negate the impact of a modern high-fat, high-sugar lifestyle"},
    {"additional-info": "Supports your body in breaking down fat, protein, plant fiber, starch, lactose and yeast."},
    {"additional-info": "Replenishes the good bacteria in your intestines"},
  ],
  "important-infos": [
    {"important-info": "Green Earth Naturals Energy Enzymes contain: lipase to <strong>break down fat</strong>, protease to <strong>break down protein</strong>, cellulase to <strong>break down plant fiber</strong>, amylase to <strong>break down starch</strong>, and lactase to <strong>break down lactose</strong>."},
    {"important-info": "This new and super enhanced formula is 2 times more potent than our original formula!"},
    {"important-info": "Suggested use: 1 with each meal, especially cooked meals."},
    {"important-info": "What are Probiotics? <strong>Pro means FOR and Biotics means LIFE</strong> - the term refers to the friendly (good) bacteria in your intestines."},
    {"important-info": "Your entire <strong>balance of health and immune protection</strong> depends upon maintaining the correct internal environment of beneficial bacteria."},
    {"important-info": "High-fat, high-sugar diets, tap water, caffeine, alcohol, antibiotics, preservatives, and even stress actively destroy your intestinal ‘friendly bacteria’."},
  ],
  "faqs": [
    {"faq-question": "HOW OFTEN IS IT RECOMMENDED TO TAKE THE ENERGY ENZYMES?",
    "faq-answer": "The Energy Enzymes are Digestive Enzymes which means they aid in the digestion of your food.  Thus it is recommended to take 1 capsule with each meal to help you break down your food better."
  },
  {"faq-question": "HOW OFTEN IS IT RECOMMENDED TO TAKE THE ENERGY PROBIOTIC DEFENSE?",
  "faq-answer": "Just 2 in the Morning to help your intestinal flora."
},
{"faq-question": "DO THESE PRODUCTS GIVE MORE ENERGY?",
"faq-answer": "Since the Energy Enzymes help break down your food, which aids in the digestion, many people feel less tired after meals, less bloated and thus more energized. The Energy Probiotic Defense contributes to it as well."
},
    ],
  "testimonial-1": "I received my order last week and just wanted to say thank you for a great product and great service! The enzyme samples are appreciated. You folks have earned yourselves a new customer as I will certainly make it a point to buy from you again in the near future.<br><br>Thanks again,",
  "testimonial-2": "I purchased your energy enzymes and am enjoying them immensely.  Wow!!!!  These are hands down the best enzymes I've ever used. I'll be buying more of your products next weekend, particularly the sample energy bar pack and the Crystal Algae.",
  "testimonial-3": "Just a note to let you know after being on the enzymes for only two days how much better my complexion is! My shoulder injury from lifting weights hurts so much less.",
  "testimonial-author-1": "- Russ K.",
  "testimonial-author-2": "- Ann R.",
  "testimonial-author-3": "- Wendy V.",
  "logo-bottom-src": "https://fs.siteor.com/wellness/files/healthHighwayNewLP/logo_17.jpg?1520429908",
  "company-descr": [
    {"paragr": "Green Earth Naturals are the exclusive worldwide distributors of Crystal Nutritionals. We are home of the organic Blue Green Algae from Klamath Lake plus Enzymes, Probiotics, and Q10."},
    ],
  "company-name": "Green Earth Naturals",
  "address": [
    {"address-line": "PO Box 5265"},
    {"address-line": "Clearwater"},
    {"address-line": "FL 33758"},
  ],
  "socials": [
    {"link": "",
      "src": ""},
    {"link": "",
      "src": ""},
    {"link": "",
      "src": ""},
  ],
  "address-2": "PO Box 5265",
  "address-3": "Clearwater",
  "address-4": "FL 33758",
  "address-5": "",
  "company-mail": "bluegreentoday@gmail.com",
  "company-phone": "800-447-8954",
  "facebook": "",
  "instagram": "",
  "twitter": "",
  "pinterest": "",
  "youtube": "",
  "linkedin": "",
  "googleplus": "",
  "copyright": "Green Earth Naturals",



  "logo-src": "https://fs.siteor.com/wellness/files/manukaNewLP/images/logejszyn_shop.png?1519388923",
  "join-src": "https://fs.siteor.com/wellness/files/manukaNewLP/images/LOGA.png?1519388845",
  "basket-src": "https://fs.siteor.com/wellness/files/newLPmodel/images/basket.png?1519202772",
  "sale-src": "https://fs.siteor.com/wellness/files/newLPmodel/images/sale.png?1519202782",
  "arrow-src": "https://fs.siteor.com/wellness/files/newLPmodel/images/arrow.png?1519202772",
  "facebook-src": "",
  "instagram-src": "",
  "twitter-src": "",
  "pinterest-src": "",
  "youtube-src": "",
  "linkedin-src": "",
  "googleplus-src": ""

}
